// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1:string):Promise<void>;

export function Inject():Promise<Array<string>>;

export function LsCamera():Promise<Array<string>>;

export function UnInject():Promise<Array<string>>;
