// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function Inject() {
  return window['go']['main']['App']['Inject']();
}

export function LsCamera() {
  return window['go']['main']['App']['LsCamera']();
}

export function UnInject() {
  return window['go']['main']['App']['UnInject']();
}
